### ISSUE TITLE
kfp --endpoint parameter

### ISSUE THREAD

**Issue by czmar** [yaginu/weather-app#5]
Hi yaginu,

Thanks for your sharing. Here I have a question regarding of the kfp --endpoint and following parameters.

For example, in your source code, you added the:

```
   -e $EXPERIMENT_NAME \
    -r $RUN_ID \
    -p $PIPELINE_ID \
    project_id=$PROJECT_ID \
    gcs_root=$GCS_STAGING_PATH \
    region=$REGION \
    source_table_name=$SOURCE_TABLE \
    num_epochs_hypertune=$NUM_EPOCHS_HYPERTUNE \
    num_epochs_retrain=$NUM_EPOCHS_RETRAIN \
    num_units=$NUM_UNITS \
    evaluation_metric_name=$EVALUATION_METRIC \
    evaluation_metric_threshold=$EVALUATION_METRIC_THRESHOLD \
    model_id=$MODEL_ID \
    version_id=$VERSION_ID \
    replace_existing_version=$REPLACE_EXISTING_VERSION
```

But I cannot find the document or reference from either Google or kubeflow how to use this **kfp cli** tools.

Could you tell me any resources?

**Comment by yaginu** [comment]
Hi czmar,

Unfortunately it may not seem that the document has enough info...https://www.kubeflow.org/docs/components/pipelines/sdk/sdk-overview/#kubeflow-pipelines-cli-tool

You can refer to cli's source code. 
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/run.py
The following are predefined in the source code. you can see the other in it. (ex. -f, -w)
```
   -e $EXPERIMENT_NAME \
   -r $RUN_ID \
   -p $PIPELINE_ID \
```
On the other hand, the following are user-defined args passing the pipeline you define.

```
    project_id=$PROJECT_ID \
    gcs_root=$GCS_STAGING_PATH \
    region=$REGION \
    source_table_name=$SOURCE_TABLE \
    num_epochs_hypertune=$NUM_EPOCHS_HYPERTUNE \
    num_epochs_retrain=$NUM_EPOCHS_RETRAIN \
    num_units=$NUM_UNITS \
    evaluation_metric_name=$EVALUATION_METRIC \
    evaluation_metric_threshold=$EVALUATION_METRIC_THRESHOLD \
    model_id=$MODEL_ID \
    version_id=$VERSION_ID \
    replace_existing_version=$REPLACE_EXISTING_VERSION
```

```python: weather-app/pipeline/model_training_pipeline.py
# Defining the pipeline
@kfp.dsl.pipeline(
    name='Weather-forecast Model Training',
    description='The pipeline training and deploying the Weather-forecast pipeline'
)
def weather_forecast_train(
        project_id,
        gcs_root,
        region,
        source_table_name,
        num_epochs_hypertune,
        num_epochs_retrain,
        num_units,
        evaluation_metric_name,
        evaluation_metric_threshold,
        model_id,
        version_id,
        replace_existing_version,
        hypertune_settings=HYPERTUNE_SETTINGS):
```

And these may help you.
https://www.coursera.org/learn/mlops-fundamentals/home/week/3
https://github.com/GoogleCloudPlatform/mlops-on-gcp/tree/master/workshops/kfp-caip-sklearn/lab-02-kfp-pipeline

**Comment by czmar** [comment]
Thanks for your response, that's very helpful !
